// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"absensi-api.com/database"
	controller2 "absensi-api.com/domain/activity/controller"
	mysql2 "absensi-api.com/domain/activity/repository/mysql"
	service2 "absensi-api.com/domain/activity/service"
	"absensi-api.com/domain/user/controller"
	"absensi-api.com/domain/user/repository/mysql"
	"absensi-api.com/domain/user/service"
	"absensi-api.com/router"
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
)

// Injectors from injector.go:

func InitServer() *gin.Engine {
	userRepository := mysql.NewUserRepositoryImpl()
	db := database.InitDBMysql()
	validate := validator.New()
	userService := service.NewUserServiceImpl(userRepository, db, validate)
	userController := controller.NewUserControllerImpl(userService)
	activityRepository := mysql2.NewActivityRepositoryImpl()
	activityService := service2.NewActivityServiceImpl(activityRepository, db, validate)
	activityController := controller2.NewActivityControllerImpl(activityService)
	engine := router.SetupRouter(userController, activityController)
	return engine
}
